config/routes.rb
Rails.application.routes.draw do
  resources :foods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
#Eric Laroche
#foods http web api

class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:REF_DATE, :GEO, :DGUID, :Foodcategories, :Commodity, :UOM, :UOM_ID, :SCALAR_FACTOR, :SCALAR_ID, :VECTOR, :COORDINATE, :VALUE)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
#Eric Laroche
# Create new food form
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :REF_DATE %>
    <%= form.text_field :REF_DATE %>
  </div>

  <div class="field">
    <%= form.label :GEO %>
    <%= form.text_field :GEO %>
  </div>

  <div class="field">
    <%= form.label :DGUID %>
    <%= form.text_field :DGUID %>
  </div>

  <div class="field">
    <%= form.label :Foodcategories %>
    <%= form.text_field :Foodcategories %>
  </div>

  <div class="field">
    <%= form.label :Commodity %>
    <%= form.text_field :Commodity %>
  </div>

  <div class="field">
    <%= form.label :UOM %>
    <%= form.text_field :UOM %>
  </div>

  <div class="field">
    <%= form.label :UOM_ID %>
    <%= form.text_field :UOM_ID %>
  </div>

  <div class="field">
    <%= form.label :SCALAR_FACTOR %>
    <%= form.text_field :SCALAR_FACTOR %>
  </div>

  <div class="field">
    <%= form.label :SCALAR_ID %>
    <%= form.text_field :SCALAR_ID %>
  </div>

  <div class="field">
    <%= form.label :VECTOR %>
    <%= form.text_field :VECTOR %>
  </div>

  <div class="field">
    <%= form.label :COORDINATE %>
    <%= form.text_field :COORDINATE %>
  </div>

  <div class="field">
    <%= form.label :VALUE %>
    <%= form.text_field :VALUE %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
#Eric Laroche
# render food edit page
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
#Eric Laroche
#/foods
#list all rows of db

<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>ROW_ID</th>
      <th>Ref date</th>
      <th>Geo</th>
      <th>Dguid</th>
      <th>Foodcategories</th>
      <th>Commodity</th>
      <th>Uom</th>
      <th>Uom id</th>
      <th>Scalar factor</th>
      <th>Scalar id</th>
      <th>Vector</th>
      <th>Coordinate</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.id %></td>
        <td><%= food.REF_DATE %></td>
        <td><%= food.GEO %></td>
        <td><%= food.DGUID %></td>
        <td><%= food.Foodcategories %></td>
        <td><%= food.Commodity %></td>
        <td><%= food.UOM %></td>
        <td><%= food.UOM_ID %></td>
        <td><%= food.SCALAR_FACTOR %></td>
        <td><%= food.SCALAR_ID %></td>
        <td><%= food.VECTOR %></td>
        <td><%= food.COORDINATE %></td>
        <td><%= food.VALUE %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
#Eric Laroche
#new food page wrapper
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
#Eric Laroche
# show indvidual food page

<p id="notice"><%= notice %></p>

<p>
  <strong>ROW_ID:</strong>
  <%= @food.ROW_ID %>
</p>
<p>
  <strong>Ref date:</strong>
  <%= @food.REF_DATE %>
</p>

<p>
  <strong>Geo:</strong>
  <%= @food.GEO %>
</p>

<p>
  <strong>Dguid:</strong>
  <%= @food.DGUID %>
</p>

<p>
  <strong>Foodcategories:</strong>
  <%= @food.Foodcategories %>
</p>

<p>
  <strong>Commodity:</strong>
  <%= @food.Commodity %>
</p>

<p>
  <strong>Uom:</strong>
  <%= @food.UOM %>
</p>

<p>
  <strong>Uom id:</strong>
  <%= @food.UOM_ID %>
</p>

<p>
  <strong>Scalar factor:</strong>
  <%= @food.SCALAR_FACTOR %>
</p>

<p>
  <strong>Scalar id:</strong>
  <%= @food.SCALAR_ID %>
</p>

<p>
  <strong>Vector:</strong>
  <%= @food.VECTOR %>
</p>

<p>
  <strong>Coordinate:</strong>
  <%= @food.COORDINATE %>
</p>

<p>
  <strong>Value:</strong>
  <%= @food.VALUE %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>